### ISSUE TITLE
Creating a Migrator

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/school-domain-querying#6]
https://github.com/flatiron-school-curriculum/school-domain-querying/blob/master/lib/student.rb#L17

I think it might be interesting to try to create a separate migrator for our tables. The issue I see with this is timing with the tests. I had some issues where my code was loaded before my migrations ran when setting up the dynamic-orm solution. We might be able to get around it by making the migrations run when they get loaded (as opposed to run), and force it to load first.

A side this this opens up is we can get away from listing properties: https://github.com/flatiron-school-curriculum/school-domain-querying/blob/master/lib/student.rb#L2

...and can do something like `db.table_info('students').map {|column| [column["name"], column["type"]]}.to_h` instead.

@aviflombaum, what do you think?

```
class StudentMigrator < FI::Migrator
  create_table students do |t|
    t.integer :id
    t.string :name
  end
end
```

Might be too much, but maybe just a class that works like `Migrator.create_table(:students, {id: :integer, name: :string})`

**Comment by AnnJohn** [comment]
I think we can add labs (this is @aviflombaum btw) that have students build Migrators but let's leave things in this complex enough lab alone.
